// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/alertas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alertas/index.get').default>>>>
    }
    '/api/auth/cambiarPass': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/cambiarPass/index').default>>>>
    }
    '/api/auth/crear-cuenta': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/crear-cuenta/index').default>>>>
    }
    '/api/auth/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login/index').default>>>>
    }
    '/api/categoria/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categoria/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categoria/[id].patch').default>>>>
    }
    '/api/categoria': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categoria/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categoria/index.post').default>>>>
    }
    '/api/estadoConservacion/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/estadoConservacion/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/estadoConservacion/[id].patch').default>>>>
    }
    '/api/estadoConservacion': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/estadoConservacion/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/estadoConservacion/index.post').default>>>>
    }
    '/api/estados': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/estados/index').default>>>>
    }
    '/api/exportarPdf/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/exportarPdf/[id].get').default>>>>
    }
    '/api/fecha': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fecha/index').default>>>>
    }
    '/api/idProducto': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/idProducto/index.get').default>>>>
    }
    '/api/nivelEducativo/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nivelEducativo/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nivelEducativo/[id].patch').default>>>>
    }
    '/api/nivelEducativo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nivelEducativo/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nivelEducativo/index.post').default>>>>
    }
    '/api/procedencia/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procedencia/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procedencia/[id].patch').default>>>>
    }
    '/api/procedencia': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procedencia/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procedencia/index.post').default>>>>
    }
    '/api/productos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/[id].patch').default>>>>
    }
    '/api/productos/agregarStock': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/agregarStock/index.post').default>>>>
    }
    '/api/productos/asignarResponsable/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/asignarResponsable/[id].patch').default>>>>
    }
    '/api/productos/asignarResponsable': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/asignarResponsable/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/asignarResponsable/index.post').default>>>>
    }
    '/api/productos/asignarSala': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/asignarSala/index.post').default>>>>
    }
    '/api/productos/editar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/editar/index.get').default>>>>
    }
    '/api/productos/filtrarSala/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/filtrarSala/[id].get').default>>>>
    }
    '/api/productos/filtrarSala/filtrarSalaEditar/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/filtrarSala/filtrarSalaEditar/[id].get').default>>>>
    }
    '/api/productos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/index.post').default>>>>
    }
    '/api/productos/nuevoProducto': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/nuevoProducto/index.post').default>>>>
    }
    '/api/productos/obtenerProductosDevolucion/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/obtenerProductosDevolucion/[id].get').default>>>>
    }
    '/api/productos/obtenerProductosSelect': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/obtenerProductosSelect/index.get').default>>>>
    }
    '/api/productos/obtenerProductosTotales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productos/obtenerProductosTotales/index.get').default>>>>
    }
    '/api/proveedores/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proveedores/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proveedores/[id].patch').default>>>>
    }
    '/api/proveedores': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proveedores/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/proveedores/index.post').default>>>>
    }
    '/api/reportes/obtenerTotales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reportes/obtenerTotales/index.get').default>>>>
    }
    '/api/reportes/productoMasUtilizado': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reportes/productoMasUtilizado/index.get').default>>>>
    }
    '/api/reportes/productoResponsable': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reportes/productoResponsable/index.get').default>>>>
    }
    '/api/reportes/productoSala': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reportes/productoSala/index.get').default>>>>
    }
    '/api/roles': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/roles/index').default>>>>
    }
    '/api/salas/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salas/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salas/[id].patch').default>>>>
    }
    '/api/salas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salas/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salas/index.post').default>>>>
    }
    '/api/subCategoria/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subCategoria/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subCategoria/[id].patch').default>>>>
    }
    '/api/subCategoria': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subCategoria/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subCategoria/index.post').default>>>>
    }
    '/api/usuarios/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/usuarios/[id].patch').default>>>>
    }
    '/api/usuarios/cambiarPassUsuario': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/usuarios/cambiarPassUsuario/index').default>>>>
    }
    '/api/usuarios': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/usuarios/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/usuarios/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
  }
}
export {}